### PR TITLE
[Feature] tmp/stop.txt

### PR DESCRIPTION
**Pull request by skull-squadron**
## Install (for testing)

``` ruby
# Gemfile
gem 'foreman_god', github: 'steakknife/foreman_god', branch: 'feature__stop.txt'
```
### To down the process

`touch tmp/stop.txt`
### To restart the process

`rm -f tmp/stop.txt`
## Proof or it didn't happen -v

Specs seem busted, so the stupid monkey workaround.
#### Procfile.foreman_god

``` ruby
#!/usr/bin/env bundle exec god -D -c
# vim: set filetype=ruby:
# mostly just for standalone production and dev
require 'foreman_god'

ForemanGod.watch File.dirname(__FILE__) do |w|
  w.name = 'foreman'
  w.start = 'bundle exec foreman start'
  w.keepalive
end
```
#### Procfile

`web: bundle exec puma -p $PORT`
#### Stopping

```
I [2014-02-25 18:02:08]  INFO: RubyClipper-web-1 [ok] (ForemanRestartFileTouched)
I [2014-02-25 18:02:12]  INFO: RubyClipper-web-1 [ok] (ForemanStopFileExists)
I [2014-02-25 18:02:13]  INFO: RubyClipper-web-1 [ok] (ForemanRestartFileTouched)
I [2014-02-25 18:02:17]  INFO: RubyClipper-web-1 [trigger] (ForemanStopFileExists)  <<< touch tmp/stop.txt
I [2014-02-25 18:02:17]  INFO: RubyClipper-web-1 move 'up' to 'stop'
I [2014-02-25 18:02:17]  INFO: RubyClipper-web-1 stop: default lambda killer
I [2014-02-25 18:02:17]  INFO: RubyClipper-web-1 sent SIGTERM
I [2014-02-25 18:02:18]  INFO: RubyClipper-web-1 process stopped
I [2014-02-25 18:02:18]  INFO: RubyClipper-web-1 moved 'up' to 'stop'
I [2014-02-25 18:02:18]  INFO: RubyClipper-web-1 [ok] (ForemanStopFileDoesntExist)
I [2014-02-25 18:02:23]  INFO: RubyClipper-web-1 [ok] (ForemanStopFileDoesntExist)
```
#### Starting

```
I [2014-02-25 18:05:34]  INFO: RubyClipper-web-1 [ok] (ForemanStopFileDoesntExist) 
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 [trigger] (ForemanStopFileDoesntExist) <<< rm -f tmp/stop.txt
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 move 'stop' to 'restart'
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 stop: default lambda killer
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 sent SIGTERM
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 process stopped
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 start: bundle exec puma -p 5000
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 moved 'stop' to 'restart'
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 [trigger] process is running (ProcessRunning)
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 move 'restart' to 'up'
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 moved 'restart' to 'up'
I [2014-02-25 18:05:39]  INFO: RubyClipper-web-1 [ok] (ForemanStopFileExists)
```

### CODE REVIEW

**Comment by rkistner** [comment]
I assume the specs fail because the current version of god doesn't support `:stop`. Can you make it work with the current version of god (without support for the stop file, but not breaking completely)?

I'm thinking something along the lines of the following:

```
if God.transitions.include? :stop # Not sure what the check should be here
  w.transition(:up, :stop) do
    ...
  end
end
```

**Comment by skull-squadron** [comment]
Not directly possible because :stop is not an user-allowed transition.  Besides, there's an open god issue to support a "down" state, and this one hack is simple, works and all god test cases pass.—

**Comment by skull-squadron** [comment]
Boom, pushes a hack for regular god.  God can go her own way on the "down" issue.—

**Comment by skull-squadron** [comment]
Stop (`touch tmp/stop.txt`) and start (`rm -f tmp/stop.txt`) verified working on regular `gem 'god'`.

**Comment by rkistner** [comment]
Thanks!

I made a small change so that the constant is not reassigned (makes Ruby 1.9.x happy).

**Pull request merged**
